---
# tasks file for sysctl configurations
- name: ensure copy sysctl configurations
  copy:
    src: "etc/sysctl.d/{{ item }}"
    dest: "/etc/sysctl.d/{{ item }}"
    mode: 0600
    owner: root
  register: sysctl
  with_items:
    - cis-section_03_level1.conf
  notify: "restart sysctl"
  tags: section03
