---
# tasks file for section05
- name: ensure install the openssh server
  apt:
    pkg: openssh-server
    state: present
  tags: section05

- name: ensure copy ssh configurations
  copy:
    src: "etc/ssh/{{ item }}"
    dest: "/etc/ssh/{{ item }}"
    mode: 0600
    owner: root
  register: ssh
  with_items:
    - ssh_config
    - sshd_config
  notify: "restart ssh"
  tags: section05
