---
# tasks file for section06
- name: ensure directory /snap/bin exist
  file:
    path: /snap/bin
    state: directory
    mode: 0755
  tags: section06

- name: ensure set the home directory permission
  file:
    path: /home/molecule
    mode: 0700
  tags: section06
