---
# tasks file for section02
- name: ensure install the OpenBSD NTP daemon
  apt:
    pkg: openntpd
    state: present
  notify: "restart openntpd"
  tags: section02

- name: ensure disable rsync
  systemd:
    name: rsync
    enabled: false
    masked: true
  tags: section02

- name: ensure remove rsync
  apt:
    pkg: rsync
    state: absent
  tags: section02

- name: ensure remove telnet
  apt:
    pkg: telnet
    state: absent
  tags: section02
