---
# handlers file for ansible-role-ubuntu-hardening
- name: ensure apply sysctl configurations
  systemd:
    name: systemd-sysctl
    state: restarted
    enabled: true
  listen: "restart sysctl"

- name: ensure restart openntpd
  systemd:
    name: openntpd
    state: restarted
    enabled: true
  listen: "restart openntpd"
