---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: ubuntu:16.04
    image_version: latest
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: cis-benchmark
verifier:
  name: goss
  lint:
    name: yamllint
