---
dependency:
  name: galaxy
driver:
  name: azure
  location: eastus2
  resource_group_name: molecule
lint:
  name: yamllint
platforms:
  - name: UbuntuServer16.04
    image_offer: UbuntuServer
    image_publisher: Canonical
    image_sku: 16.04-LTS
    image_version: latest
    vm_size: Standard_A0
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
scenario:
  name: cis-benchmark
  list_sequence:
    - lint
  test_sequence:
    - lint
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: goss
  lint:
    name: yamllint
